### ISSUE TITLE
Can't remove output.js (Windows)

### ISSUE THREAD

**Issue by boisgera** [boisgera/pandoc#13]
$ ./build
Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    doc = pandoc.read(file=doc_file)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\site-packages\pandoc-1.1.0-py3.7.egg\pandoc\__init__.py", line 292, in read
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus: 'C:\\Users\\boisgera\\AppData\\Local\\Temp\\tmp4byi8_00\\output.js'
Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    doc = pandoc.read(file=doc_file)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\site-packages\pandoc-1.1.0-py3.7.egg\pandoc\__init__.py", line 292, in read
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus: 'C:\\Users\\boisgera\\AppData\\Local\\Temp\\tmp1zra6gfa\\output.js'
Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    doc = pandoc.read(file=doc_file)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\site-packages\pandoc-1.1.0-py3.7.egg\pandoc\__init__.py", line 292, in read
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus: 'C:\\Users\\boisgera\\AppData\\Local\\Temp\\tmpf9gy18tb\\output.js'
Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    doc = pandoc.read(file=doc_file)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\site-packages\pandoc-1.1.0-py3.7.egg\pandoc\__init__.py", line 292, in read
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus: 'C:\\Users\\boisgera\\AppData\\Local\\Temp\\tmp4q3eaiwh\\output.js'
Traceback (most recent call last):
  File "./build.py", line 39, in <module>
    doc = pandoc.read(file=doc_file)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\site-packages\pandoc-1.1.0-py3.7.egg\pandoc\__init__.py", line 292, in read
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 513, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 397, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\boisgera\sandbox\control-engineering-with-python\env\lib\shutil.py", line 395, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] Le processus ne peut pas acc▒der au fichier car ce fichier est utilis▒ par un autre processus: 'C:\\Users\\boisgera\\AppData\\Local\\Temp\\tmpih0pyixb\\output.js'

**Comment by boisgera** [comment]
fix: 5077ea22aeae8cbacfb5a2387e3851d07d204ae1
