### ISSUE TITLE
Doesn't really install on windows

### ISSUE THREAD

**Issue by ionelmc** [boisgera/pandoc#5]
```
C:\Users\ionel_000\Projects\ropython-site>.env\Scripts\pip install pandoc
Collecting pandoc
  Downloading pandoc-1.0.0a8.tar.gz (511kB)
    100% |################################| 512kB 975kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\ionel_~1\appdata\local\temp\pip-build-akcqzx\pandoc\setup.py", line 27, in <module>
        import about
      File "c:\users\ionel_~1\appdata\local\temp\pip-build-akcqzx\pandoc\.lib\about\__init__.py", line 17, in <module>
        import sh
      File "c:\users\ionel_~1\appdata\local\temp\pip-build-akcqzx\pandoc\.lib\sh.py", line 37, in <module>
        support." % __version__)
    ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\ionel_~1\appdata\local\temp\pip-build-akcqzx\pandoc

C:\Users\ionel_000\Projects\ropython-site>.env\Scripts\pip install pbs
Collecting pbs
  Downloading pbs-0.110.tar.gz
Installing collected packages: pbs
  Running setup.py install for pbs
Successfully installed pbs-0.110

C:\Users\ionel_000\Projects\ropython-site>.env\Scripts\pip install pandoc
Collecting pandoc
  Using cached pandoc-1.0.0a8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\ionel_~1\appdata\local\temp\pip-build-oahruy\pandoc\setup.py", line 27, in <module>
        import about
      File "c:\users\ionel_~1\appdata\local\temp\pip-build-oahruy\pandoc\.lib\about\__init__.py", line 17, in <module>
        import sh
      File "c:\users\ionel_~1\appdata\local\temp\pip-build-oahruy\pandoc\.lib\sh.py", line 37, in <module>
        support." % __version__)
    ImportError: sh 1.11 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\ionel_~1\appdata\local\temp\pip-build-oahruy\pandoc
```

**Comment by thomasleveil** [comment]
@ionelmc have you figured this out by chance?

**Comment by ionelmc** [comment]
@thomasleveil not really, sorry. I'm just using subprocess (https://github.com/RoPython/ropython-site/blob/master/import-meetup.py#L111-L115) - seems easy enough.

**Comment by boisgera** [comment]
It should work now.
